name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Push to GitHub Feed
      env:
        ORG_GITHUB_PACKAGES_PASSWORD:  ${{ secrets.ORG_GITHUB_PACKAGES_PASSWORD }}
      shell: bash
      run: |
        for f in /home/runner/work/hubee-service-discovery-sdk/hubee-service-discovery-sdk/src/Hubee.ServiceDiscovery.Sdk/bin/Release/*.nupkg
        do
          dotnet nuget push "$f" --source "https://nuget.pkg.github.com/HubeePlatform/index.json" -k $ORG_GITHUB_PACKAGES_PASSWORD --skip-duplicate
        done